#include <string>

#include <unordered_map>

const char* openDrtTooltipForParam(const std::string& name) {
  static const std::unordered_map<std::string, const char*> kTooltips = {
    {"tn_Lp", "Peak display luminance in nits. SDR maps peak to 1.0, HDR maps peak to the selected container level."},
    {"tn_gb", "Amount of stops to boost grey luminance per stop of peak luminance increase."},
    {"pt_hdr", "How much purity compression and hue shift behavior changes as peak luminance increases."},
    {"tn_Lg", "Display luminance for middle grey (0.18) in nits."},
    {"lookPreset", "Select a look preset. This applies look controls, while independent tonescale and creative-white selections are preserved."},
    {"tonescalePreset", "Select a tonescale preset. Changing look selects the corresponding tonescale preset automatically."},
    {"creativeWhitePreset", "Select creative whitepoint. Changing look updates this to the corresponding look whitepoint."},
    {"cwp_lm", "Limit the intensity range affected by Creative Whitepoint."},
    {"displayEncodingPreset", "Choose a target viewing environment preset (EOTF, gamut, surround, and clamp defaults)."},
    {"tn_con", "Tonescale contrast (display-linear slope control)."},
    {"tn_sh", "Tonescale shoulder control; affects where highlights approach peak and clip."},
    {"tn_toe", "Shadow toe compression amount."},
    {"tn_off", "Scene-linear offset applied before tonescale."},
    {"tn_hcon_enable", "Enable highlight contrast shaping."},
    {"tn_hcon", "Highlight contrast amount."},
    {"tn_hcon_pv", "Stops above middle grey where highlight adjustment starts."},
    {"tn_hcon_st", "Highlight contrast transition strength/ramp-in speed."},
    {"tn_lcon_enable", "Enable low/mid contrast shaping."},
    {"tn_lcon", "Low-contrast module amount."},
    {"tn_lcon_w", "Low-contrast width (how broad the affected range is)."},
    {"rs_sa", "Render-space color-contrast amount (desaturates toward weighted luminance axis)."},
    {"rs_rw", "Render-space red weight."},
    {"rs_bw", "Render-space blue weight."},
    {"pt_enable", "Enable purity compression at higher intensities."},
    {"pt_lml", "Purity compression limit as intensity decreases (all hues)."},
    {"pt_lml_r", "Purity compression limit as intensity decreases (reds)."},
    {"pt_lml_g", "Purity compression limit as intensity decreases (greens)."},
    {"pt_lml_b", "Purity compression limit as intensity decreases (blues)."},
    {"pt_lmh", "Purity compression limit as intensity increases (all hues)."},
    {"pt_lmh_r", "Purity compression limit as intensity increases (reds)."},
    {"pt_lmh_b", "Purity compression limit as intensity increases (blues)."},
    {"ptl_enable", "Enable purity softclip to reduce hard clipping near gamut boundaries."},
    {"ptl_c", "Purity softclip strength for cyan."},
    {"ptl_m", "Purity softclip strength for magenta."},
    {"ptl_y", "Purity softclip strength for yellow."},
    {"ptm_enable", "Enable mid-purity shaping controls."},
    {"ptm_low", "Amount to raise mid-purity in low/mid intensity regions."},
    {"ptm_low_rng", "Range for low/mid mid-purity shaping."},
    {"ptm_low_st", "Strength weighting for low/mid mid-purity shaping."},
    {"ptm_high", "Amount to reduce mid-purity in upper-mid/high intensity regions."},
    {"ptm_high_rng", "Range for high mid-purity shaping."},
    {"ptm_high_st", "Strength weighting for high mid-purity shaping."},
    {"brl_enable", "Enable Brilliance (pre-compression purity-intensity shaping)."},
    {"brl", "Global brilliance amount for high-purity stimuli."},
    {"brl_r", "Brilliance amount for red stimuli."},
    {"brl_g", "Brilliance amount for green stimuli."},
    {"brl_b", "Brilliance amount for blue stimuli."},
    {"brl_rng", "Brilliance range over intensity (higher values affect lower intensities more)."},
    {"brl_st", "Brilliance strength over purity (higher values affect lower purity more)."},
    {"brlp_enable", "Enable Post Brilliance (after purity compression/hue shifts)."},
    {"brlp", "Global post-brilliance amount."},
    {"brlp_r", "Post-brilliance amount for red; useful to reduce high-purity ringing/halos."},
    {"brlp_g", "Post-brilliance amount for green; useful to reduce high-purity ringing/halos."},
    {"brlp_b", "Post-brilliance amount for blue; useful to reduce high-purity ringing/halos."},
    {"hc_enable", "Enable Hue Contrast shaping."},
    {"hc_r", "Hue contrast amount at red hue angle."},
    {"hc_r_rng", "Hue contrast range control over intensity."},
    {"hs_rgb_enable", "Enable RGB hue-shift module (primary hue-angle distortion as intensity increases)."},
    {"hs_r", "Red hue-shift amount (toward yellow)."},
    {"hs_r_rng", "Range of red hue-shift."},
    {"hs_g", "Green hue-shift amount (toward yellow)."},
    {"hs_g_rng", "Range of green hue-shift."},
    {"hs_b", "Blue hue-shift amount (toward cyan)."},
    {"hs_b_rng", "Range of blue hue-shift."},
    {"hs_cmy_enable", "Enable CMY hue-shift module (secondary hue-angle distortion as intensity decreases)."},
    {"hs_c", "Cyan hue-shift amount (toward blue)."},
    {"hs_c_rng", "Range of cyan hue-shift."},
    {"hs_m", "Magenta hue-shift amount (toward blue)."},
    {"hs_m_rng", "Range of magenta hue-shift."},
    {"hs_y", "Yellow hue-shift amount (toward red)."},
    {"hs_y_rng", "Range of yellow hue-shift."},
    {"clamp", "Clamp final image to display-supported range."},
    {"tn_su", "Surround compensation mode (dark, dim, bright)."},
    {"display_gamut", "Target display gamut (typically Rec.709 for SDR or Rec.2020/P3 for HDR)."},
    {"eotf", "Target display transfer function (Linear, power, PQ, or HLG)."},
    {"crv_enable", "Draw tonescale overlay for curve debugging/inspection."},
  };
  auto it = kTooltips.find(name);
  return it == kTooltips.end() ? nullptr : it->second;
}
