# Parse VERSION for bundle stem, version_gen.h, and Info.plist placeholders.
file(STRINGS "${CMAKE_SOURCE_DIR}/VERSION" OPENDRT_VERSION_LINE LIMIT_COUNT 1)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/VERSION")
string(REGEX REPLACE "\r" "" OPENDRT_VERSION_LINE "${OPENDRT_VERSION_LINE}")
string(REGEX MATCH "^[0-9]+\\.[0-9]+\\.[0-9]+" OPENDRT_TRIPLET "${OPENDRT_VERSION_LINE}")
if(NOT OPENDRT_TRIPLET)
  message(FATAL_ERROR "VERSION first line must start with major.minor.patch")
endif()

string(LENGTH "${OPENDRT_TRIPLET}" _opendrt_tlen)
string(SUBSTRING "${OPENDRT_VERSION_LINE}" "${_opendrt_tlen}" -1 _opendrt_rest)
string(STRIP "${_opendrt_rest}" OPENDRT_VERSION_SUFFIX)
if(OPENDRT_VERSION_SUFFIX STREQUAL "")
  set(OPENDRT_PLUGIN_VERSION_STR "${OPENDRT_TRIPLET}")
else()
  set(OPENDRT_PLUGIN_VERSION_STR "${OPENDRT_TRIPLET} ${OPENDRT_VERSION_SUFFIX}")
endif()

string(REPLACE "." ";" _opendrt_ver_parts "${OPENDRT_TRIPLET}")
list(GET _opendrt_ver_parts 0 OPENDRT_VER_MAJOR)
list(GET _opendrt_ver_parts 1 OPENDRT_VER_MINOR)
list(GET _opendrt_ver_parts 2 OPENDRT_VER_PATCH)

set(OPENDRT_DISPLAY_VERSION "${OPENDRT_TRIPLET}")
set(PLUGIN_OFX_IDENTIFIER "com.lsp.simple_open_drt")
set(OPENDRT_OFX_BUNDLE_STEM "LSP_Simple_Open_DRT_${OPENDRT_DISPLAY_VERSION}")
set(OPENDRT_OFX_EXECUTABLE_NAME "${OPENDRT_OFX_BUNDLE_STEM}.ofx")
set(PLUGIN_BASENAME "${OPENDRT_OFX_BUNDLE_STEM}")
set(OPENDRT_RELEASE_FOLDER_MACOS "${OPENDRT_OFX_BUNDLE_STEM}_macos")
set(OPENDRT_RELEASE_FOLDER_WINDOWS "${OPENDRT_OFX_BUNDLE_STEM}_windows")
set(OPENDRT_RELEASE_FOLDER_LINUX "${OPENDRT_OFX_BUNDLE_STEM}_linux")

set(OPENDRT_VERSION_GEN "${CMAKE_SOURCE_DIR}/plugin/version_gen.h")

configure_file(
  "${CMAKE_SOURCE_DIR}/cmake/version_gen.h.in"
  "${OPENDRT_VERSION_GEN}"
  @ONLY
)

set(PLUGIN_NUMERIC_VERSION "${OPENDRT_TRIPLET}")
set(PLUGIN_DISPLAY_VERSION "${OPENDRT_PLUGIN_VERSION_STR}")
set(OFX_EXECUTABLE_NAME "${OPENDRT_OFX_EXECUTABLE_NAME}")

add_custom_target(opendrt_gen_version ALL DEPENDS "${OPENDRT_VERSION_GEN}")
